import { EmergencyReport, Alert, Volunteer, ReliefRequest, SatarkPointTransaction, WeatherData } from '@/types';

export const INITIAL_WEATHER: WeatherData = {
  city: 'Kathmandu Valley',
  temp: 22,
  condition: 'Heavy Monsoonal Rainfall',
  conditionNp: 'भारी मनसुनी वर्षा',
  rainProbability: 85,
  windSpeed: 24,
  forecast: 'Continued heavy precipitation expected in Bagmati province for the next 12 hours.',
  isDemo: true,
};

export const INITIAL_REPORTS: EmergencyReport[] = [
  {
    id: 'SR-782910',
    userName: 'Aarav Sharma',
    userPhone: '+977 9841234567',
    type: 'flood',
    description: 'Bishnumati River overflowed near Gongabu bridge. Water entering lower level residential houses. 8 families trapped on top floors.',
    latitude: 27.7335,
    longitude: 85.3122,
    address: 'Gongabu, Bishnumati Corridor, Kathmandu',
    priority: 'critical',
    status: 'RESPONDING',
    trustLevel: 'HIGH',
    trustDetails: {
      gpsVerified: true,
      recentSubmission: true,
      mediaAttached: true,
      humanVerified: true,
      aiStatus: 'Verified',
    },
    aiVerification: {
      status: 'Verified',
      confidence: 94,
      observations: [
        'Image shows active river overflow matching Bishnumati bridge architecture',
        'Timestamp & GPS metadata align perfectly',
        'No digital editing artifacts detected'
      ],
      recommendation: 'Priority high rescue dispatch recommended.'
    },
    mediaUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?q=80&w=800&auto=format&fit=crop',
    mediaType: 'photo',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'SR-492102',
    userName: 'Saraswati Adhikari',
    userPhone: '+977 9808765432',
    type: 'landslide',
    description: 'Fresh mudslide blocking Tribhuvan Highway near Nagdhunga. Massive debris layer, vehicles unable to pass in either direction.',
    latitude: 27.6920,
    longitude: 85.2050,
    address: 'Nagdhunga Pass, Kathmandu West',
    priority: 'critical',
    status: 'VERIFIED',
    trustLevel: 'HIGH',
    trustDetails: {
      gpsVerified: true,
      recentSubmission: true,
      mediaAttached: true,
      humanVerified: true,
      aiStatus: 'Verified',
    },
    aiVerification: {
      status: 'Verified',
      confidence: 89,
      observations: [
        'Mud debris blockage observed on highway',
        'Matches known slope instability zone'
      ],
      recommendation: 'Notify Heavy Equipment Operators immediately.'
    },
    mediaUrl: 'https://images.unsplash.com/photo-1508873696983-2df515122519?q=80&w=800&auto=format&fit=crop',
    mediaType: 'photo',
    createdAt: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'SR-112044',
    userName: 'Bikram Gurung',
    userPhone: '+977 9812348901',
    type: 'road',
    description: 'Tree fallen over electrical line at Lakeside main road Pokhara. Road partially blocked, risk of live wire.',
    latitude: 28.2096,
    longitude: 83.9586,
    address: 'Lakeside Ward 6, Pokhara',
    priority: 'urgent',
    status: 'UNDER REVIEW',
    trustLevel: 'MEDIUM',
    trustDetails: {
      gpsVerified: true,
      recentSubmission: true,
      mediaAttached: false,
      humanVerified: false,
      aiStatus: 'Needs Review',
    },
    aiVerification: {
      status: 'Needs Review',
      confidence: 68,
      observations: [
        'Text description clear',
        'No photo evidence attached to verify wire danger'
      ],
      recommendation: 'Human confirmation with local Pokhara ward required.'
    },
    createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'SR-663912',
    userName: 'Kabita Thapa',
    userPhone: '+977 9860112233',
    type: 'fire',
    description: 'Kitchen gas cylinder burst in 3-story residential building near Patan Durbar area. Smoke billowed.',
    latitude: 27.6730,
    longitude: 85.3250,
    address: 'Mangal Bazaar, Lalitpur',
    priority: 'critical',
    status: 'RESOLVED',
    trustLevel: 'HIGH',
    trustDetails: {
      gpsVerified: true,
      recentSubmission: true,
      mediaAttached: true,
      humanVerified: true,
      aiStatus: 'Verified',
    },
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    isDemo: true,
  }
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'ALT-101',
    title: 'RED ALERT: Flash Flood Warning for Hanumante & Bagmati Rivers',
    titleNp: 'अति उच्च जोखिम: हनुमन्ते र बागमती नदी तटीय क्षेत्रमा बाढीको चेतावनी',
    description: 'Continuous torrential rain over Bagmati basin. Water levels crossing danger mark in Bhaktapur & South Lalitpur. Citizens in low-lying riparian corridors advised to move to higher ground shelters.',
    descriptionNp: 'बागमती जलाधार क्षेत्रमा लगातार भारी वर्षा। भक्तपुर र ललितपुरका तटीय क्षेत्र जोखिममा।',
    type: 'flood',
    severity: 'high',
    location: 'Kathmandu Valley (Bhaktapur, Lalitpur, Ktm)',
    source: 'Official Emergency Agency',
    verified: true,
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'ALT-102',
    title: 'LANDSLIDE ADVISORY: Prithvi Highway Corridor',
    titleNp: 'पहिरो चेतावनी: पृथ्वी राजमार्ग क्षेत्र',
    description: 'Slopes vulnerable near Malekhu and Mugling. Travel only if necessary during heavy downpours.',
    descriptionNp: 'मलेखु र मुग्लिन क्षेत्रमा पहिरोको उच्च जोखिम। सतर्कता अपनाउनुहोला।',
    type: 'landslide',
    severity: 'moderate',
    location: 'Prithvi Highway / Dhading - Chitwan',
    source: 'Satark Verified',
    verified: true,
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    isDemo: true,
  }
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  {
    id: 'VOL-001',
    userId: 'USR-881',
    userName: 'Rohan Shrestha',
    phone: '+977 9841998877',
    area: 'Patan / Lalitpur',
    skills: ['First Aid', 'Rescue', 'Transportation'],
    availability: 'Immediate (24/7)',
    verified: true,
    points: 420,
    rank: 'Satark Hero',
    reportsVerifiedCount: 14,
    reliefTasksCompleted: 8,
    isDemo: true,
  },
  {
    id: 'VOL-002',
    userId: 'USR-882',
    userName: 'Pooja Karki',
    phone: '+977 9811223344',
    area: 'Bhaktapur Ward 4',
    skills: ['Food Distribution', 'Medical', 'Communication'],
    availability: 'Daytime',
    verified: true,
    points: 310,
    rank: 'Guardian',
    reportsVerifiedCount: 9,
    reliefTasksCompleted: 6,
    isDemo: true,
  },
  {
    id: 'VOL-003',
    userId: 'USR-883',
    userName: 'Deepak Rai',
    phone: '+977 9803456789',
    area: 'Pokhara Lakeside',
    skills: ['Rescue', 'Logistics'],
    availability: 'On Call',
    verified: true,
    points: 185,
    rank: 'Responder',
    reportsVerifiedCount: 5,
    reliefTasksCompleted: 3,
    isDemo: true,
  }
];

export const INITIAL_RELIEF_REQUESTS: ReliefRequest[] = [
  {
    id: 'REL-501',
    createdBy: 'Bhaktapur Community Shelter',
    contactPhone: '+977 9851099887',
    type: 'food',
    description: 'Dry food packs (Beaten rice, noodles, biscuits) and clean drinking water needed for 45 flood displaced families staying at Birendra Sainik campus assembly ground.',
    location: 'Suryabinayak, Bhaktapur',
    urgency: 'critical',
    peopleAffected: 45,
    currentResponders: 2,
    status: 'IN PROGRESS',
    assignedVolunteers: ['VOL-002'],
    helpRecords: [],
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    isDemo: true,
  },
  {
    id: 'REL-502',
    createdBy: 'Red Cross Lalitpur Unit',
    contactPhone: '+977 9841887766',
    type: 'medicine',
    description: 'First aid bandage supplies, ORS packets, and basic fever medicine needed at Nakkhu corridor community clinic.',
    location: 'Nakkhu Dobhan, Lalitpur',
    urgency: 'urgent',
    peopleAffected: 20,
    currentResponders: 1,
    status: 'NEEDED',
    helpRecords: [],
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    isDemo: true,
  }
];

export const INITIAL_TRANSACTIONS: SatarkPointTransaction[] = [
  {
    id: 'TX-901',
    userId: 'USR-881',
    points: 30,
    reason: 'Completed flood rescue coordination task at Bishnumati corridor',
    reasonNp: 'विष्णुमती बाढी उद्धार कार्य सफलतापूर्वक पूरा गरिएको',
    referenceType: 'relief',
    referenceId: 'REL-501',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'TX-902',
    userId: 'USR-881',
    points: 20,
    reason: 'Submitted verified high-priority flood emergency report SR-782910',
    reasonNp: 'प्रमाणित उच्च-प्राथमिकता बाढी रिपोर्ट दर्ता गरिएको',
    referenceType: 'report',
    referenceId: 'SR-782910',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  }
];
